### ISSUE TITLE
Plugin issue

### ISSUE THREAD

**Issue by caposseleDigicat** [FIWARE-TMForum/business-ecosystem-charging-backend#48]
After updating to the new version I am not able to load any plugin. After the load command I get the error: CommandError: No module named plugins.basic-service.basic_url.BasicPlugin. Before the instruction "return getattr(__import__(module_package, globals(), locals(), [module_class_name], -1), module_class_name)" is called  in the plugin_loader.py the content of the variables module, module_class_name and module_package is:
module: wstore.asset_manager.resource_plugins.plugins.basic-service.basic_url.BasicPlugin
module_class_name: BasicPlugin
module_package: wstore.asset_manager.resource_plugins.plugins.basic-service.basic_url

**Comment by caposseleDigicat** [comment]
The problem was a missing __init__.py inside the folder wstore/asset_manager/resource_plugins/plugins

**Comment by emepetres** [comment]
The issue hasn't been fixed in the docker image

**Comment by fdelavega** [comment]
you are right, the __init__.py file dissapear when the volume is bound to an empty folder, since the contents are overriden by the host directory
